question_data = [{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games", "question": "Nintendo started out as a playing card manufacturer.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Politics",
                  "question": "The S in Harry S. Truman stands for 'Samuel'.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Board Games",
                  "question": "'Rich Uncle Pennybags' from the board game 'Monopoly' wears a monocle.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Sports",
                  "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                  "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Sports",
                  "question": "Formula E is an auto racing series that uses hybrid electric race cars.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Gadgets",
                  "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
                  "question": "In 'Star Trek', Klaang is a typical Klingon male.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Animals",
                  "question": "The Killer Whale is considered a type of dolphin.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In 'Undertale', the main character of the game is Sans.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                  "question": "In Rocket League, you can play Basketball.", "correct_answer": "True", "incorrect_answers": ["False"]}
                 ]
